#!/bin/bash
if [ $# -lt 2 ]
then
  echo >&2 "This script builds a source archive (as produced by cabal sdist)"
  echo >&2 "Usage: $0 sourcefile.tar.gz builddir..."
  exit 1
fi

file=$(realpath "$1")
shift

if [ ! -e "$file" ]
then
  echo >&2 "$file does not exist"
  exit 1
fi

set -ex -o pipefail

for dir
do
  tagfile="$dir/tag"
  if [ ! -e "$tagfile" ]
  then
    echo >&2 "$tagfile does not exist"
    exit 2
  fi

  docker_args=()
  if [ -e "$dir/use-local-build-script" ]
  then
    build_script=$(realpath "$dir/build")
    docker_args+=(--mount "type=bind,src=$build_script,dst=/usr/bin/build,readonly")
  fi

  docker run -i "${docker_args[@]}" "$(< "$tagfile")" < "$file" | tar xz
done
